FROM public.ecr.aws/docker/library/node:18-slim

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Start the application
CMD ["node", "server.js"]
